spring.application.name=demoparty

# Server configuration
server.port=8080
server.address=0.0.0.0

# WebSocket configuration
spring.websocket.allowed-origins=*

# Logging
logging.level.root=INFO
logging.level.com.bekirhatip.demoparty=DEBUG

# Write logs to a file. path/name can be overridden by environment or command-line
# Example: -Dlogging.file.name=/var/log/demoparty.log or set LOG_FILE_NAME env var
logging.file.name=${LOG_FILE_NAME:/logs/demoparty.log}
